# COMMANDED ALL THE PROPERTIES AS WE ARE GOING TO MOVE FROM LOCAL PROFILES TO CLOUD CONFIG PROFILES

#spring:
#  config:
#    activate:
#      on-profile: "qa"
#
#build:
#  version: "2.0"
#
#accounts:
#  message: "Welcome to HansBank accounts related QA APIs "
#  contactDetails:
#    name: "Smitha Ray - QA Lead"
#    email: "smitha@eazybank.com"
#  onCallSupport:
#    - (666) 265-3765
#    - (666) 734-8371