server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
#  datasource:
#    url: jdbc:mysql://localhost:3305/accountsdb
#    username: root
#    password: root

  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  sql:
#    init:
#      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"
#  profiles:
#    active: "qa"


#build:
#  version: 3.0
#
#accounts:
#  message: "Welcome to HansBank accounts related local APIs "
#  contactDetails:
#    name: "John Doe - Developer"
#    email: "john@eazybank.com"
#  onCallSupport:
#        - (555) 555-1234
#        - (555) 523-1345
