
# COMMANDED ALL THE PROPERTIES AS WE ARE GOING TO MOVE FROM LOCAL PROFILES TO CLOUD CONFIG PROFILES



#spring:
#  config:
#    activate:
#      on-profile: "prod"
#
#build:
#  version: "1.0"
#
#accounts:
#  message: "Welcome to EazyBank accounts related prod APIs "
#  contactDetails:
#    name: "Reine Aishwarya - Product Owner"
#    email: "aishwarya@eazybank.com"
#  onCallSupport:
#    - (453) 392-4829
#    - (236) 203-0384